In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'col1':[1,2,3,4,5],
             'col2': [45,56,67,34,34],
             'col3': "Roshan Zameer Learning in ineuron".split()})

In [3]:
df

col1  col2      col3
0     1    45    Roshan
1     2    56    Zameer
2     3    67  Learning
3     4    34        in
4     5    34   ineuron

In [4]:
df['col4'] =  df['col1']**2

In [5]:
df

col1  col2      col3  col4
0     1    45    Roshan     1
1     2    56    Zameer     4
2     3    67  Learning     9
3     4    34        in    16
4     5    34   ineuron    25

In [6]:
df['col5'] = df['col3'].str[0]

In [7]:
df

col1  col2      col3  col4 col5
0     1    45    Roshan     1    R
1     2    56    Zameer     4    Z
2     3    67  Learning     9    L
3     4    34        in    16    i
4     5    34   ineuron    25    i

In [8]:
def test(a):
    return a**2

In [9]:
df['col4_4'] = df['col1'].apply(test)

In [10]:
df

col1  col2      col3  col4 col5  col4_4
0     1    45    Roshan     1    R       1
1     2    56    Zameer     4    Z       4
2     3    67  Learning     9    L       9
3     4    34        in    16    i      16
4     5    34   ineuron    25    i      25

In [11]:
def test2(a):
    if a == "R":
        return "R"
    else:
        return "Z"

In [12]:
df['col6'] = df['col5'].apply(test2)

In [13]:
df

col1  col2      col3  col4 col5  col4_4 col6
0     1    45    Roshan     1    R       1    R
1     2    56    Zameer     4    Z       4    Z
2     3    67  Learning     9    L       9    Z
3     4    34        in    16    i      16    Z
4     5    34   ineuron    25    i      25    Z

In [14]:
df['col6_6'] = df['col5'].apply(lambda a: 'R' if a=='R' else "Z")

In [15]:
df

col1  col2      col3  col4 col5  col4_4 col6 col6_6
0     1    45    Roshan     1    R       1    R      R
1     2    56    Zameer     4    Z       4    Z      Z
2     3    67  Learning     9    L       9    Z      Z
3     4    34        in    16    i      16    Z      Z
4     5    34   ineuron    25    i      25    Z      Z

In [16]:
df['col7'] = df['col3'].apply(len)

In [17]:
import math

In [18]:
df['col8'] = df['col2'].apply(math.log)

In [19]:
df

col1  col2      col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    45    Roshan     1    R       1    R      R     6  3.806662
1     2    56    Zameer     4    Z       4    Z      Z     6  4.025352
2     3    67  Learning     9    L       9    Z      Z     8  4.204693
3     4    34        in    16    i      16    Z      Z     2  3.526361
4     5    34   ineuron    25    i      25    Z      Z     7  3.526361

In [20]:
import numpy as np

In [21]:
l = ["shan",1,2,3,4]

In [22]:
type(l)

list

In [23]:
array = np.array(l)

In [24]:
type(array)

numpy.ndarray

In [25]:
a1 =np.array([3,4,5,6,3.0])

In [26]:
a = np.array([[1,2],[3,4]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
a[1][1]

4

In [29]:
a1[1]

4.0

In [30]:
a2 =np.array([1,2,3,4],ndmin=4)

In [31]:
a2

array([[[[1, 2, 3, 4]]]])

In [32]:
a2[0][0][0][3]

4

In [33]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [34]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [35]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [36]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [37]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [38]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [39]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [40]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
np.mat(np.fromfunction(lambda i , j : i*j , (4,4),dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [42]:
np.fromfunction(lambda i , j, z : i*j*z , (3,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [45]:
a = np.fromfunction(lambda i , j, z : i*j*z , (4,3,2),dtype = int)

In [46]:
a.ndim

3

In [47]:
a.size

24

In [48]:
a.shape

(4, 3, 2)

In [49]:
a.dtype

dtype('int32')

In [50]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [51]:
import pandas as pd

In [54]:
a = np.fromfunction(lambda i , j : i*j , (3,2),dtype = int)

In [55]:
pd.DataFrame(a)

0  1
0  0  0
1  0  1
2  0  2

In [56]:
a = np.fromfunction(lambda i , j : i*j , (400,100),dtype = int)

In [57]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [58]:
np.random.rand(100,4)

array([[0.17880876, 0.49967318, 0.95846095, 0.13921761],
       [0.60978192, 0.92448163, 0.4292608 , 0.40498284],
       [0.57508727, 0.01063918, 0.88989734, 0.96003063],
       [0.30625063, 0.77068004, 0.94614994, 0.13630541],
       [0.46391685, 0.23323168, 0.40900046, 0.60697412],
       [0.3860654 , 0.26136354, 0.51963564, 0.74659964],
       [0.43275911, 0.46173386, 0.5878777 , 0.79628177],
       [0.99903558, 0.15721852, 0.51544409, 0.76702582],
       [0.66353667, 0.95767982, 0.74706203, 0.43676181],
       [0.44381372, 0.87841142, 0.63385614, 0.14497817],
       [0.85592068, 0.9034106 , 0.49072879, 0.3733363 ],
       [0.27457769, 0.13314256, 0.40933684, 0.05501934],
       [0.95963093, 0.28610669, 0.44666073, 0.6629936 ],
       [0.73597274, 0.59931059, 0.99851774, 0.97409595],
       [0.81699737, 0.93395159, 0.8046466 , 0.19715233],
       [0.65539031, 0.74543606, 0.19671162, 0.00459858],
       [0.38580572, 0.41536378, 0.10145228, 0.44679514],
       [0.79138518, 0.80883699,

In [61]:
np.random.randint(4,50)

37

In [62]:
np.random.randn(4,5)

array([[-0.69103226, -0.18935769, -0.34811153, -0.70086011, -2.68694327],
       [-0.74950803,  1.43410909,  1.06375541, -1.27298468, -0.10793634],
       [-0.37536242, -1.22031046, -1.03057274,  1.33199736,  0.3259083 ],
       [-0.83441146,  0.44110358, -0.43322231, -0.22322553, -1.436945  ]])

In [63]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.016264 -0.300406 -1.110652  0.209205 -0.871466
1  0.113302  0.744953 -0.280225  1.247651 -1.972817
2 -0.658167  0.667379  1.831633 -1.501241  0.756745
3 -0.275786  0.189877  0.641471  1.062233  0.513210

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [65]:
a = np.fromfunction(lambda i , j, z : i*j*z , (4,3,2),dtype = int)

In [66]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [68]:
a.shape

(4, 3, 2)

In [69]:
a.size

24

In [73]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [74]:
a.reshape(6,-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [75]:
a.reshape(6,-1464646)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [77]:
list(range(4,10,2))

[4, 6, 8]

In [78]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [80]:
a1 = np.arange(4,10,.2)

In [81]:
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [82]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [83]:
arr = np.random.rand(4,5)

In [84]:
arr

array([[0.16564156, 0.61519311, 0.59800896, 0.06641151, 0.62225743],
       [0.71182643, 0.76142352, 0.44974702, 0.73570575, 0.97480198],
       [0.79581603, 0.68418455, 0.22836319, 0.3486551 , 0.4571286 ],
       [0.82850008, 0.48148204, 0.23396721, 0.88555065, 0.49769098]])

In [86]:
arr[arr > 0.5]

array([0.61519311, 0.59800896, 0.62225743, 0.71182643, 0.76142352,
       0.73570575, 0.97480198, 0.79581603, 0.68418455, 0.82850008,
       0.88555065])

In [87]:
arr

array([[0.16564156, 0.61519311, 0.59800896, 0.06641151, 0.62225743],
       [0.71182643, 0.76142352, 0.44974702, 0.73570575, 0.97480198],
       [0.79581603, 0.68418455, 0.22836319, 0.3486551 , 0.4571286 ],
       [0.82850008, 0.48148204, 0.23396721, 0.88555065, 0.49769098]])

In [88]:
arr[[1,2],[2]]

array([0.44974702, 0.22836319])

In [91]:
df = pd.DataFrame(arr)

In [92]:
df

0         1         2         3         4
0  0.165642  0.615193  0.598009  0.066412  0.622257
1  0.711826  0.761424  0.449747  0.735706  0.974802
2  0.795816  0.684185  0.228363  0.348655  0.457129
3  0.828500  0.481482  0.233967  0.885551  0.497691

In [93]:
df.iloc[[1,2],[2]]

2
1  0.449747
2  0.228363

In [94]:
arr = np.random.rand(8,5)

In [95]:
arr

array([[0.53097013, 0.55946877, 0.91570405, 0.89111201, 0.5314324 ],
       [0.24350428, 0.58556391, 0.26541695, 0.30356004, 0.12956389],
       [0.03354066, 0.96859127, 0.02304826, 0.67550054, 0.06063224],
       [0.86170977, 0.42753337, 0.02351857, 0.68662406, 0.5284939 ],
       [0.0398206 , 0.28782005, 0.66676361, 0.38965002, 0.78260153],
       [0.74239777, 0.83930412, 0.18052506, 0.09325953, 0.36794327],
       [0.50919764, 0.59278279, 0.76304712, 0.35298848, 0.96958434],
       [0.97489471, 0.0869958 , 0.75601231, 0.47212979, 0.45993776]])

In [97]:
arr[1:8,0:3]

array([[0.24350428, 0.58556391, 0.26541695],
       [0.03354066, 0.96859127, 0.02304826],
       [0.86170977, 0.42753337, 0.02351857],
       [0.0398206 , 0.28782005, 0.66676361],
       [0.74239777, 0.83930412, 0.18052506],
       [0.50919764, 0.59278279, 0.76304712],
       [0.97489471, 0.0869958 , 0.75601231]])

In [98]:
a2 =arr[1:8,0:3]

In [99]:
a2

array([[0.24350428, 0.58556391, 0.26541695],
       [0.03354066, 0.96859127, 0.02304826],
       [0.86170977, 0.42753337, 0.02351857],
       [0.0398206 , 0.28782005, 0.66676361],
       [0.74239777, 0.83930412, 0.18052506],
       [0.50919764, 0.59278279, 0.76304712],
       [0.97489471, 0.0869958 , 0.75601231]])

In [100]:
a2[0][0] = 23456

In [101]:
a2

array([[2.34560000e+04, 5.85563912e-01, 2.65416945e-01],
       [3.35406574e-02, 9.68591269e-01, 2.30482555e-02],
       [8.61709767e-01, 4.27533375e-01, 2.35185668e-02],
       [3.98205992e-02, 2.87820054e-01, 6.66763608e-01],
       [7.42397766e-01, 8.39304120e-01, 1.80525062e-01],
       [5.09197643e-01, 5.92782791e-01, 7.63047124e-01],
       [9.74894707e-01, 8.69958040e-02, 7.56012310e-01]])

In [102]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [103]:
a

array([[1, 2],
       [3, 4]])

In [104]:
b

array([[2, 3],
       [4, 5]])

In [106]:
# element wise multiplication
a*b

array([[ 2,  6],
       [12, 20]])

In [108]:
#Matrix multiplication

m = a@b

In [109]:
m

array([[10, 13],
       [22, 29]])

In [110]:
m/0

C:\Users\Munna\AppData\Local\Temp\ipykernel_8960\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])