In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [5]:
type(np.asarray(l))

numpy.ndarray

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
#Broadcasting
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.empty((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [17]:
np.logspace(2,4,10,base=12)

array([  144.        ,   250.13850321,   434.50882493,   754.77352153,
        1311.09665931,  2277.47052728,  3956.13242226,  6872.09057374,
       11937.32256987, 20736.        ])

In [20]:
a = np.arange(16).reshape(4,4)

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
a.max()

15

In [24]:
a = np.arange(4,20).reshape(4,4)

In [25]:
a.max()

19

In [26]:
a = np.arange(4,40).reshape(3,6,2)

In [27]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [28]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [29]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [30]:
10+a

array([[[14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37]],

       [[38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [31]:
a/0

C:\Users\Munna\AppData\Local\Temp\ipykernel_12504\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]],

       [[inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf],
        [inf, inf]]])

In [32]:
a**2

array([[[  16,   25],
        [  36,   49],
        [  64,   81],
        [ 100,  121],
        [ 144,  169],
        [ 196,  225]],

       [[ 256,  289],
        [ 324,  361],
        [ 400,  441],
        [ 484,  529],
        [ 576,  625],
        [ 676,  729]],

       [[ 784,  841],
        [ 900,  961],
        [1024, 1089],
        [1156, 1225],
        [1296, 1369],
        [1444, 1521]]])

In [33]:
pow(a,2)

array([[[  16,   25],
        [  36,   49],
        [  64,   81],
        [ 100,  121],
        [ 144,  169],
        [ 196,  225]],

       [[ 256,  289],
        [ 324,  361],
        [ 400,  441],
        [ 484,  529],
        [ 576,  625],
        [ 676,  729]],

       [[ 784,  841],
        [ 900,  961],
        [1024, 1089],
        [1156, 1225],
        [1296, 1369],
        [1444, 1521]]])

In [37]:
b = np.array([2,3,1,2,3,2])

In [35]:
b

array([2, 3, 1, 2, 3])

In [38]:
a = np.arange(4,40).reshape(6,6)

In [39]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])